### ISSUE TITLE
[Beta feedback] Donate Activity finishes unexpectedly

### ISSUE THREAD

**Issue by alexstyl** [alexstyl/Memento-Calendar#154]
Donate Activity -> click donate Button  --> open Dialog ---> press back
meta pataw pali sto Donate button
psofaei to activity
me warning

```
09-07 20:13:57.158 30064-30064/? W/System.err: com.alexstyl.specialdates.donate.a.b$a: Can't dispose because an async operation (launchPurchaseFlow) is in progress.
09-07 20:13:57.158 30064-30064/? W/System.err:     at com.alexstyl.specialdates.donate.a.b.a(IabHelper.java:324)
09-07 20:13:57.159 30064-30064/? W/System.err:     at com.alexstyl.specialdates.donate.b.a(AndroidDonationService.java:66)
09-07 20:13:57.159 30064-30064/? W/System.err:     at com.alexstyl.specialdates.donate.h.a(DonatePresenter.java:40)
09-07 20:13:57.159 30064-30064/? W/System.err:     at com.alexstyl.specialdates.donate.DonateActivity.onDestroy(DonateActivity.java:121)
```

**Comment by alexstyl** [comment]
No longer relevant.
