### ISSUE TITLE
Birthday on February 29,2017 is not displayed

### ISSUE THREAD

**Issue by auricgoldfinger** [alexstyl/Memento-Calendar#83]
#### Short Description

_App currently in Play Store crashes on Marshmallow, custom rom_

##### Steps to reproduce
 1. Open app from home screen's icon
FYI: There's a contact that has his birthday on 29th of february.

##### Resulted in
App crashes.

> _More details in case that could matter: My XPeria Z was acting fishy and especially gave a lot of bluetooth problems. That much that my bluetooth headset stopped working. Before buying another phone, I decided to unlock the bootloader and flash another rom. I chose StryFlex - an AOSP Marshmallow based ROM, based on the original Sony rom for the XPeria ZX. The phone is working smoothly now and I have no more issues._
>
> _Except for Memento_ 😉

I checked out the most recent code, build and installed that one to see whether I could solve the problem myself. But that build works smoothly, **except for the fact that the contact isn't displayed**

FYI: I am using dummy `crashlyticsKey`, `androidVendingKey` and `mixpanelKey` here and I even commented out `apply plugin: 'com.google.gms.google-services'` in mobile/build.gradle to work around the missing `google-services.json`. So maybe the error is somewhere inthere?

So I sent the crash report anyway. Maybe you can find the cause... Since it's obfuscated, I can't read the stacktrace :-)

At the end of this post is the logcat **for the app installed using the Google Play Store**. I included the entire logcat from the moment I start the application, not just the exception

For now, I'm going to install your `all_events_create_event` branch on my phone, for which I'm very grateful :-)

##### logcat
```
01-21 14:11:42.064 645-3717/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.alexstyl.specialdates/.ui.activity.MainActivity (has extras)} from uid 10117 on display 0
01-21 14:11:42.347 645-21331/system_process I/ActivityManager: Start proc 30884:com.alexstyl.specialdates/u0a187 for activity com.alexstyl.specialdates/.ui.activity.MainActivity
01-21 14:11:42.465 30884-30884/com.alexstyl.specialdates W/System: ClassLoader referenced unknown path: /data/app/com.alexstyl.specialdates-1/lib/arm
01-21 14:11:42.494 30884-30884/com.alexstyl.specialdates D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
01-21 14:11:42.503 30884-30884/com.alexstyl.specialdates D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
01-21 14:11:42.523 30884-30884/com.alexstyl.specialdates I/FA: App measurement is starting up, version: 9683
01-21 14:11:42.524 30884-30884/com.alexstyl.specialdates I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
01-21 14:11:42.551 30884-30884/com.alexstyl.specialdates I/FA: To enable faster debug mode event logging run:
                                                                 adb shell setprop firebase.analytics.debug-mode com.alexstyl.specialdates
01-21 14:11:42.568 30884-30884/com.alexstyl.specialdates I/FirebaseInitProvider: FirebaseApp initialization successful
01-21 14:11:42.642 30884-30884/com.alexstyl.specialdates W/d: diskCache() and diskCacheFileNameGenerator() calls overlap each other
01-21 14:11:42.733 30884-30884/com.alexstyl.specialdates I/CrashlyticsCore: Initializing Crashlytics 2.3.8.97
01-21 14:11:42.785 30884-30895/com.alexstyl.specialdates I/art: Background partial concurrent mark sweep GC freed 17599(1282KB) AllocSpace objects, 18(360KB) LOS objects, 72% free, 1565KB/5MB, paused 14.007ms total 40.679ms
01-21 14:11:42.841 30884-30913/com.alexstyl.specialdates W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
01-21 14:11:42.939 30884-30884/com.alexstyl.specialdates W/MixpanelAPI.RsrcReader: Can't load names for Android view ids from 'com.alexstyl.specialdates.R$id', ids by name will not be available in the events editor.
01-21 14:11:42.939 30884-30884/com.alexstyl.specialdates I/MixpanelAPI.RsrcReader: You may be missing a Resources class for your package due to your proguard configuration, or you may be using an applicationId in your build that isn't the same as the package declared in your AndroidManifest.xml file.
                                                                                   If you're using proguard, you can fix this issue by adding the following to your proguard configuration:
                                                                                   
                                                                                   -keep class **.R$* {
                                                                                       <fields>;
                                                                                   }
                                                                                   
                                                                                   If you're not using proguard, or if your proguard configuration already contains the directive above, you can add the following to your AndroidManifest.xml file to explicitly point the Mixpanel library to the appropriate library for your resources class:
                                                                                   
                                                                                   <meta-data android:name="com.mixpanel.android.MPConfig.ResourcePackageName" android:value="YOUR_PACKAGE_NAME" />
                                                                                   
                                                                                   where YOUR_PACKAGE_NAME is the same string you use for the "package" attribute in your <manifest> tag.
01-21 14:11:42.970 30884-30884/com.alexstyl.specialdates D/MixpanelAPI.AL: To enable App Links tracking android.support.v4 must be installed: getInstance [class android.content.Context]
01-21 14:11:42.971 30884-30884/com.alexstyl.specialdates D/MixpanelAPI.AL: Please install the Bolts library >= 1.1.2 to track App Links: bolts.AppLinks
01-21 14:11:43.125 30884-30884/com.alexstyl.specialdates W/MixpanelAPI.ConfigurationChecker: com.mixpanel.android.surveys.a is not registered as an activity in your application, so surveys can't be shown.
01-21 14:11:43.125 30884-30884/com.alexstyl.specialdates I/MixpanelAPI.ConfigurationChecker: Please add the child tag <activity android:name="com.mixpanel.android.surveys.SurveyActivity" /> to your <application> tag.
01-21 14:11:43.197 30884-30937/com.alexstyl.specialdates D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-21 14:11:43.293 30884-30937/com.alexstyl.specialdates I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
01-21 14:11:43.297 30884-30937/com.alexstyl.specialdates I/OpenGLRenderer: Initialized EGL, version 1.4
01-21 14:11:43.471 645-664/system_process I/ActivityManager: Displayed com.alexstyl.specialdates/.ui.activity.MainActivity: +1s145ms
01-21 14:11:43.644 30884-30903/com.alexstyl.specialdates I/FA: Tag Manager is not found and thus will not be used
                                                               
                                                               --------- beginning of crash
01-21 14:11:45.338 30884-30935/com.alexstyl.specialdates E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
                                                                           Process: com.alexstyl.specialdates, PID: 30884
                                                                           java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                               at android.support.v4.b.k$3.done(ModernAsyncTask.java:161)
                                                                               at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                               at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: java.lang.IllegalArgumentException: 29/2/2017 is invalid
                                                                               at com.alexstyl.specialdates.c.c.a(Date.java:48)
                                                                               at com.alexstyl.specialdates.events.b.b$a.a(PeopleEventsContract.java:55)
                                                                               at com.alexstyl.specialdates.events.b.b$a.a(PeopleEventsContract.java:30)
                                                                               at com.alexstyl.specialdates.service.a.b(PeopleEventsProvider.java:193)
                                                                               at com.alexstyl.specialdates.service.a.a(PeopleEventsProvider.java:149)
                                                                               at com.alexstyl.specialdates.upcoming.l.B(UpcomingEventsLoader.java:59)
                                                                               at com.alexstyl.specialdates.upcoming.l.d(UpcomingEventsLoader.java:29)
                                                                               at android.support.v4.b.a.e(AsyncTaskLoader.java:299)
                                                                               at android.support.v4.b.a$a.a(AsyncTaskLoader.java:57)
                                                                               at android.support.v4.b.a$a.a(AsyncTaskLoader.java:45)
                                                                               at android.support.v4.b.k$2.call(ModernAsyncTask.java:138)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                               at java.lang.Thread.run(Thread.java:818) 
01-21 14:11:45.345 645-21331/system_process W/ActivityManager:   Force finishing activity com.alexstyl.specialdates/.ui.activity.MainActivity
01-21 14:11:45.354 30884-30893/com.alexstyl.specialdates W/CursorWrapperInner: Cursor finalized without prior close()
01-21 14:11:46.125 30884-30916/com.alexstyl.specialdates I/CrashlyticsCore: Crashlytics report upload complete: 58835E0E030B-0001-78A4-2590DBC70216.cls

```

**Comment by auricgoldfinger** [comment]
Maybe #84 might be a solution? Or is that a too short cut :-)

**Comment by alexstyl** [comment]
Hi @auricgoldfinger . Many thanks for your detailed log. 

The year 2017 does not have the 29/2 date as it is not leap year. I never considered such a scenario to be honest. There have been a lot of modifications around dates in the latest builds and that's why the app is not crashing but the contact is hidden; because the date does not make sense. 

When do you usually send your wishes to your friends that celebrate on that day? 
I am wondering if Memento should still display a card for that day, as if the day existed. I wouldn't want to move the date of the event to some different event as that way you would be displaying the wrong information.

**Comment by auricgoldfinger** [comment]
True. 
If I was in the situation, I'd choose 1st of March because that is in my opinion more correct: x years ago, that person wasn't born yet on February 28, but on the next day. The next day is March 1 in most cases. There are however people who choose to celebrate it on February 28. So maybe it's a good choice to display the card on both days? It is a strange situation indeed 😀

**Comment by auricgoldfinger** [comment]
... to be complete: Google Calendar displays the birthday on February 28...

**Comment by auricgoldfinger** [comment]
Yeah but remember: the app that is currently published on the play store does crash in this case ;-)
(probably not such a big issue because there won't be a lot of users who have contacts born on February 29)

**Comment by alexstyl** [comment]
The next market ready version of the app is close to finishing. As a lot of things have been changed to how the app handles the dates to display, it is not just a stand-alone fix that can be shipped just yet

**Comment by auricgoldfinger** [comment]
True.
Take your time :-)

**Comment by alexstyl** [comment]
Closing as a won't do out of inactivity
